### ISSUE TITLE
FoxService tries to create the db tables

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxServerSide#4]
It fails because the user is read only, but it should not be trying to do that.

I think this is an issue if it starts before the server.

**Comment by ac2cz** [comment]
We also get crazy file names with the word ALERT appended over and over:
FoxWebService20180111.log.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT.ALERT

**Comment by ac2cz** [comment]
We got this error because it could not connect to the DB server.  I guess that triggered the "Exception" that meant a table was not there.  So it tried to create it.
It then tries to write an error to the decoder log and failed that too. Full error below:

20180112154140:
---SQLException Caught--- Caused by: createTable:Fox1RADTELEMETRY

20180112154140: SQLState: 08001
20180112154140: Severity: 0
20180112154140: Message: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
        at sun.reflect.GeneratedConstructorAccessor8.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.Util.getInstance(Util.java:387)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:862)
        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2164)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2089)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
        at sun.reflect.GeneratedConstructorAccessor4.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at com.mysql.jdbc.Util.handleNewInstance(Ut
il.java:404)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriv
 at java.sql.DriverManager.getConnection(DriverManager.java:571)
        at java.sql.DriverManager.getConnection(DriverManager.java:215)
        at telemetry.PayloadDbStore.getConnection(PayloadDbStore.java:145)
        at telemetry.SatPayloadDbStore.createTable(SatPayloadDbStore.java:175)
        at telemetry.SatPayloadDbStore.initPayloadTable(SatPayloadDbStore.java:148)
        at telemetry.SatPayloadDbStore.initPayloadFiles(SatPayloadDbStore.java:129)
        at telemetry.SatPayloadDbStore.<init>(SatPayloadDbStore.java:117)
        at telemetry.PayloadDbStore.<init>(PayloadDbStore.java:129)
        at FoxService.initPayloadDB(FoxService.java:111)
        at FoxService.start(FoxService.java:91)
        at FoxService.main(FoxService.java:52)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Too many connections
        at sun.reflect.GeneratedConstructorAccessor8.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.Util.getInstance(Util.java:387)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
        at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4315)
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1259)
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2254)
        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2105)
        ... 20 more


20180112154140: ALERT: SERIOUS SQL exception caused by createTable:Fox1RADTELEMETRY.  Need to clear the ALERT and restart the server:

20180112154140: FATAL ERROR Cannot write log file: FoxTelemDecoder.log
Perhaps the disk is full or the directory is not writable:


You can reset FoxTelem by deleting the settings file (might want to back it up first):
/FoxTelem.properties
